services:
  mysql:
    image: mysql:latest
    container_name: mysql-api
    environment:
      MYSQL_DATABASE: auth
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gabriel
      MYSQL_PASSWORD: 1234
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - infra-local

  # auth-api:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - DATABASE_HOST=host.docker.internal
  #     - DATABASE_PORT=3306
  #     - DATABASE_USERNAME=gabriel
  #     - DATABASE_PASSWORD=1234
  #     - DATABASE_NAME=auth
  #   networks:
  #     - infra-local

volumes:
  mysql_data:

networks:
  infra-local:
    driver: bridge